<?php
if (!defined('APP_BOOT')) {
    http_response_code(403);
    exit('Accès direct interdit.');
}

return <<<'HTML'
<p>
    This policy explains how <strong>{app}</strong> processes personal data, in line with the GDPR
    and the French Data Protection Act. It complements the
    <a href="{cgu_url}">terms of use</a> and the
    <a href="{mentions_url}">legal notice</a>.
</p>

<h2>1. Data controller</h2>
<p>
    The controller is the publisher of {app}, identified in the
    <a href="{mentions_url}">legal notice</a>.
    For any question about your data: {contact_mailto}.
</p>
<p>
    No data protection officer (DPO) has been appointed: that is not required for processing of
    this kind and scale. The email above is the contact point.
</p>

<h2>2. Data we collect</h2>
<p>
    We collect data needed to run the service, either provided by you or generated by your use:
</p>
<ul>
    <li><strong>Account</strong> — username, optional display name, email address, password (stored
        hashed, never in plain text), dates of username or password changes, interface language,
        date the privacy policy was accepted, opt-out of non-essential emails, account status
        (active / disabled).</li>
    <li><strong>Profile</strong> — photo (a file you upload, compressed and resized), bio, favourite
        sport, favourite teams, player kit, profile backgrounds and username colours from the shop.</li>
    <li><strong>Play</strong> — predictions, points (career and season), streak, badges, shop balance
        and point-spend history, community memberships and rankings.</li>
    <li><strong>Social</strong> — chat messages (stored encrypted in the database), community names
        and descriptions (encrypted), friend relationships (requests and acceptances).</li>
    <li><strong>Notifications</strong> — if you enable them: Web Push subscription (technical VAPID
        keys), alert-type preferences.</li>
    <li><strong>Technical</strong> — session cookie, approximate last visit (to operate the service),
        limited error logs, temporary rate-limit files (hashed IP, not on the account record),
        display preferences.</li>
</ul>
<p>
    Your <strong>username</strong> (and display name), <strong>photo</strong> if any,
    <strong>points / rankings</strong> and some profile items are visible to other members on the
    relevant screens (profiles, chat, friends, rankings).
</p>
<p>
    Without an account, your slip choices may stay in the browser (localStorage) until you log in
    or delete them. We do not receive them until you confirm picks while logged in.
</p>
<p>
    We do not ask for ID documents, a full date of birth, bank cards or health data. Do not post
    that kind of information in chat or in your bio.
</p>

<h2>3. Purposes and legal bases</h2>
<ul>
    <li><strong>Performance of the contract</strong> (using the service): account creation,
        predictions, points, seasons, communities, chat, friends, cosmetic shop, strictly necessary
        emails (password reset).</li>
    <li><strong>Legitimate interest</strong>: security, abuse prevention, moderation, technical
        diagnosis, keeping a coherent game history, minimal internal usage follow-up (last visit,
        no behavioural advertising on our side).</li>
    <li><strong>Consent</strong>: push notifications, profile photo, <strong>advertising</strong>
        cookies and scripts (Google AdSense). You can withdraw consent (browser or site settings,
        cookie banner, removing the photo).</li>
    <li><strong>Legal obligation</strong> where applicable (replying to an authority, keeping what
        is strictly required).</li>
</ul>
<p>
    Game-related emails (for example a score correction that affects you, or a match reminder if
    that option is enabled on the server) may be sent. Non-essential emails respect your account
    opt-out when it exists. Password-reset emails remain possible even if you have opted out,
    because they are necessary for the account.
</p>

<h2>4. Encryption (what it is, and what it is not)</h2>
<p>
    <strong>Chat messages</strong> and <strong>community names / descriptions</strong> are stored
    encrypted in the database (AES-256-GCM) with a key kept on the server (not in the public
    repository). A raw database export does not show them in clear text without that key.
</p>
<p>
    <strong>This is not end-to-end encryption.</strong> The application decrypts this content to
    show it to authorised members. The publisher can also access it when necessary (see section 5).
    Do not treat chat as confidential vis-à-vis the publisher.
</p>

<h2>5. Administrator access</h2>
<p>
    A technical administration access, distinct from player accounts, is used to operate the service.
    In that context the publisher may:
</p>
<ul>
    <li>access message content after decryption by the application,
        <strong>only when necessary and proportionate</strong> (a report, suspected unlawful or
        harassing content, a legal obligation, a security incident, diagnosis);</li>
    <li>hide or delete content; remove an inappropriate photo;</li>
    <li>disable / re-enable an account; help reset a password;</li>
    <li>consult account data needed to run the service (username, email, points, status),
        without selling it;</li>
    <li>correct results, adjust in-game points or manage seasons.</li>
</ul>
<p>
    There is <strong>no systematic reading</strong> of all conversations.
</p>

<h2>6. Recipients</h2>
<p>{app} does not sell your data. It may be processed by:</p>
<ul>
    <li>The server and database <strong>host</strong> (identified in the
        <a href="{mentions_url}">legal notice</a>) — storage of the site, database and files
        (including photos).</li>
    <li><strong>Cloudflare, Inc.</strong> (United States) — if the site is served through that CDN /
        proxy (as on current production): connection data (IP, technical logs).
        Policy: <a href="{cloudflare_privacy}" rel="noopener noreferrer">cloudflare.com/privacypolicy</a>.</li>
    <li>The <strong>email (SMTP) provider</strong> — sending transactional messages to your address.
        When SMTP is provided by LWS, that processing takes place with this host established in France.</li>
    <li><strong>The Odds API</strong> — the server queries this API for fixtures and odds.
        <strong>No account data is sent</strong> to that third party.
        Site: <a href="{odds_url}" rel="noopener noreferrer">the-odds-api.com</a>.</li>
    <li><strong>Browser / OS push services</strong> (Web Push infrastructure from Google, Mozilla or
        Apple, depending on your browser) — only if you enable notifications; technical subscription
        data.</li>
    <li><strong>Google</strong> (fonts, and ads if you agree): see sections 7 and 8.</li>
    <li><strong>cdnjs (Cloudflare)</strong> — loading the icon library (Font Awesome) on pages that
        use it: your browser contacts that CDN (IP address).</li>
</ul>

<h2>7. Transfers outside the European Union</h2>
<p>
    The application server and database are tied to the host named in the legal notice.
    Some providers may nevertheless process data outside the EU, in particular:
</p>
<ul>
    <li>Cloudflare (CDN) — IP address and connection data;</li>
    <li>Google (fonts; AdSense if you consented; possibly Chrome push);</li>
    <li>other browser vendors for Web Push.</li>
</ul>
<p>
    These transfers rely, depending on the provider, on an adequacy decision, standard contractual
    clauses or your consent (advertising). The Odds API is queried by our server without sending
    your account data.
</p>
<p>
    We do not claim that “all data stays in the EU”, because that would be inaccurate once CDNs,
    fonts or ads from companies established outside the EU are used.
</p>

<h2 id="cookies">8. Cookies and local storage</h2>
<p>
    A <strong>banner</strong> lets you accept or refuse <strong>advertising</strong> cookies and
    scripts. Cookies that are strictly necessary for the service are set without prior consent,
    in line with CNIL guidance.
</p>
<p><strong>Strictly necessary:</strong></p>
<ul>
    <li>PHP session cookie — authentication, lasting about {session_days} days, renewed as you
        browse. Without it, login and saving predictions do not work.</li>
    <li>Language cookie (<code>prognoz_lang</code>) — remembers FR or EN, up to 13 months.</li>
    <li>Retro display cookie (<code>prognoz_ui</code>) — only if a legacy browser triggers the
        simplified layout.</li>
    <li>Onboarding cookie (<code>prognoz_onboard_hide</code>) — hides the tutorial if you dismiss it.</li>
    <li>Choice cookie (<code>prognoz_consent</code>) — stores your acceptance or refusal of
        advertising cookies, 180 days.</li>
</ul>
<p>
    The browser may also store locally (localStorage / sessionStorage), on <em>your</em> device
    only: a draft slip, a seen-beta flag, chat cursors, display preferences. That is not targeted
    advertising on our side.
</p>
<p id="publicite">
    <strong>Advertising (consent required)</strong> — if you accept, the site loads Google AdSense
    (Google publisher ID). Google may then set its own cookies and process browsing data (pages
    viewed, advertising identifiers, approximate IP) to show ads, including personalised ads
    according to Google’s settings. We do not control Google’s cookies. Policies:
    <a href="{google_privacy}" rel="noopener noreferrer">Google Privacy</a>,
    <a href="{google_ads}" rel="noopener noreferrer">Google Ads</a>.
    Settings: <a href="{ads_settings_url}" rel="noopener noreferrer">adssettings.google.com</a>.
</p>
<p>
    Refusing advertising cookies does not stop you from using the game. You can change your mind
    via the “Cookies” link in the footer. Until you choose, AdSense scripts are not loaded.
</p>
<p>
    <strong>Google Fonts</strong> — on the modern layout, the browser loads fonts from Google’s
    servers. Google may receive your IP address. That load is for display, not for us to profile you.
</p>

<h2>9. Retention</h2>
<ul>
    <li>Account, predictions, points, seasons, shop — for as long as the account is active.</li>
    <li>Chat messages — for community history (unless hidden or deleted).</li>
    <li>Profile photos — for as long as you keep them, or until removal (by you or moderation).</li>
    <li>Push subscriptions — until permission is withdrawn or the account is deleted.</li>
    <li>Password-reset tokens — valid 24 hours, then invalidated or deleted.</li>
    <li>Session — expires after inactivity or logout (see cookie lifetime above).</li>
    <li>Rate-limit files — a few hours, then overwritten.</li>
    <li>Technical logs — a limited time, for diagnosis.</li>
</ul>
<p>
    Deleting the account from <a href="{settings_url}">Settings</a> erases the account and related
    data in the production database (predictions, messages, subscriptions, etc., through database
    relations). A community you created may remain without your name as creator.
    Residual copies in technical backups may exist for a limited time, then be overwritten.
    That is not an account restore for you.
</p>
<p>
    You can also write to {contact_mailto}.
</p>

<h2>10. Your rights</h2>
<p>Under the GDPR you have in particular the following rights:</p>
<ul>
    <li>access, rectification and erasure;</li>
    <li>rectifying username, password or photo from Settings
        (subject, for username and password, to the {cooldown}-day gap between two changes);</li>
    <li>restriction or objection, in the cases provided by the regulation;</li>
    <li>portability of data you provided;</li>
    <li>withdrawing consent where processing depends on it (push, photo, advertising);</li>
    <li>instructions on what happens to your data after your death (French Data Protection Act, art. 85).</li>
</ul>
<p>
    To exercise these rights: {contact_mailto}.
    Please include your username so we can handle the request.
    You may also lodge a complaint with the CNIL
    (<a href="{cnil_url}" rel="noopener noreferrer">www.cnil.fr</a>) or another competent EU
    supervisory authority.
</p>
<p>
    The {cooldown}-day gap between username or password changes is a game security measure. It does
    not block a GDPR rectification or erasure request (including account deletion, which is possible
    at any time).
</p>

<h2>11. Minors</h2>
<p>
    The service is for people aged {min_age} or over (see the Terms).
    {min_age} is a threshold chosen because of chat and communities, higher than the age of 15
    often used in France for digital consent. We have no parental-consent flow: under {min_age},
    an account is not allowed.
</p>

<h2>12. Security</h2>
<p>
    Reasonable measures: hashed passwords, server-side encryption of messages, restricted admin
    access, API keys on the server, HttpOnly session cookies. No transmission over the Internet
    is entirely free of risk.
</p>

<h2>13. Changes to this policy</h2>
<p>
    This page is updated when data processing changes (a new feature, a new provider, etc.).
    The date at the top of the page is authoritative. A “beta” notice on the site, if any, does
    not allow processing of data that is not described here.
</p>
HTML;
